// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace DataAccess
{
    [Serializable]
    public partial class MasterCard
    {
        [Display(Name = "Card Number")]
        [Required(ErrorMessage = "Card number required")]
        [StringLength(19, ErrorMessage = "Card number must be between 16 digits", MinimumLength = 16)]
        [CreditCard]
        public string Number { get; set; }
        [Display(Name = "Expiration Date")]
        [Required(ErrorMessage = "Expiration date required")]
        public DateTime ExpirationDate { get; set; }
        [StringLength(3, ErrorMessage = "Security code must be 3 digits", MinimumLength = 3)]
        [Display(Name = "Security Code")]
        [Required(ErrorMessage = "Security code required")]
        public string SecurityCode { get; set; }
        [Display(Name = "Owner")]
        [Required(ErrorMessage = "Cad owner required")]
        [StringLength(5, ErrorMessage = "Name must be bewteen 5 and 30 characters long", MinimumLength = 30)]
        public string Owner { get; set; }
        [Display(Name = "Quota")]
        [Required(ErrorMessage = "Card quota required")]
        public int Quota { get; set; }
        [Display(Name = "Card Balance")]
        [Required(ErrorMessage = "Card balance required")]
        public int Balance { get; set; }
    }
}