// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using DataAccess;

#nullable disable

namespace DataAccess.Data
{
    public partial class CardsContext : DbContext
    {
        public CardsContext()
        {
        }

        public CardsContext(DbContextOptions<CardsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<VisaCard> VisaCard { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlServer(@"Server=DESKTOP-5KIS3PN;Database=Cards;Trusted_Connection=true");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.Entity<VisaCard>(entity =>
            {
                entity.HasKey(e => e.Number);

                entity.Property(e => e.Number)
                    .HasMaxLength(19)
                    .IsFixedLength(true);

                entity.Property(e => e.ExpirationDate).HasColumnType("date");

                entity.Property(e => e.Owner)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsFixedLength(true);

                entity.Property(e => e.SecurityCode)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsFixedLength(true);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}