// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess
{
    public partial class VisaCard
    {
        public string Number { get; set; }
        public DateTime ExpirationDate { get; set; }
        public string SecurityCode { get; set; }
        public string Owner { get; set; }
        public int Quota { get; set; }
        public int Balance { get; set; }
    }
}